### ISSUE TITLE
required steps to add  certificate

### ISSUE THREAD

**Issue by GhadaFathy** [AAROC/DevOps#228]
we got a certificate, and need to add it to idp ,science_getway , ldap servers  
 what are the steps we need to do that

**Comment by brucellino** [comment]
Hi @GhadaFathy great news :)

Since there are 3 different hosts here, I would appreciate  it if you could open a separate ticket for each of them if need be. This could however be answered generically- 

all the services are created using self-signed certificates. You simply need to replace the certificates and the trust anchors from the CA. If this is not sufficient, then we could write a brief section in the wiki.

If you have any issues with *particular hosts* then please open a ticket accordingly for that host.
thanks ! 
Bruce

**Comment by brucellino** [comment]
Closing this since there are specific tickets open for individual hosts.
