### ISSUE TITLE
required steps to add  certificate to idp

### ISSUE THREAD

**Issue by GhadaFathy** [AAROC/DevOps#229]
We got a certificate, and need to add it to idp in yml files 

what are the steps we need to do that

**Comment by brucellino** [comment]
The certificate just needs to be swapped out with the self-signed one that is generated. This can only be done manually, since the playbooks can't assume that you have the certificate when you run them. 

We don't have detailed instructions yet, but will write some soon. @fmarco76 can provide some input on where to put the certificate and what format it should be in.

**Comment by brucellino** [comment]
This has been implemented, but not not yet committed. See #232. I just need to clean the code and protect the passwords. Should be done in a few days.
