### ISSUE TITLE
SSH Error: Permission denied (publickey,password).

### ISSUE THREAD

**Issue by qasims** [AAROC/DevOps#231]
I am trying to run simple ping (ansible -m ping all) and getting following errors. Please help me what is the problem. I also tried with hostname (www.example.com) but same result.

<44.140.63.5> ESTABLISH CONNECTION FOR USER: qasim
<44.140.63.5> REMOTE_MODULE ping
<44.140.63.5> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 44.140.63.5 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435036987.58-164813461721185 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1435036987.58-164813461721185 && echo $HOME/.ansible/tmp/ansible-tmp-1435036987.58-164813461721185'
44.140.63.5 | FAILED => SSH Error: Permission denied (publickey,password).
    while connecting to 44.140.63.5:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

Here is my hosts inventory

![hosts](https://cloud.githubusercontent.com/assets/3830639/8299510/ddd9059c-1979-11e5-8917-2238354bb9d2.PNG)

Here is ansible.cfg overview.

![config1](https://cloud.githubusercontent.com/assets/3830639/8299514/f17c42c6-1979-11e5-80f3-e23b148d029c.PNG)

![config2](https://cloud.githubusercontent.com/assets/3830639/8299516/f54b2ea8-1979-11e5-962a-f18c2ab11425.PNG)

**Comment by brucellino** [comment]
hi @qasims 

this is an error with the Ansible syntax - unless you have passwordless ssh set up, you need to provide a password, and specify that Ansible should ask for it, with the `-k` flag. Of course, you will get an error with `www.example.com` since there is no such host :wink: 

If you have the hosts in the inventory up and running, you should specify their passwords either in the host variables or on the command line. See http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters


In our default model, we provide a `bootstrap.yml` playbook which creates an ansible user with priveliges and ssh key access (albeit with only certain ssh keys - we need to fix this), so that this can be used subsequently by other playbooks.
