### ISSUE TITLE
Child group is not defined

### ISSUE THREAD

**Issue by mekuanent** [AAROC/DevOps#356]
Configuration Issue

ERROR: child group is not defined: (idp.ethernet.edu.et)

Here is bash code
ansible-playbook -i inventories/inventory.ethernet.edu.et idp-ldap.yml shibv3idp-ldap.yml

**Comment by brucellino** [comment]
Hi @mekuanent thanks for reporting the issue. I'm going to try and reproduce it.

**Comment by brucellino** [comment]
Sorry, I missed  this error in the code-review (and we don't test for this... so I'm thinking of updating the travis tests). 
There was a problem with your inventory. You included single hosts in a `:children` definition - however, the children need to be defined as groups. I've included the site group instead of the individual hosts.

**Comment by mekuanent** [comment]
Another Issue Bruce
ERROR: become is not a legal parameter in an Ansible task or handler

**Comment by brucellino** [comment]
hi @mekuanent - please open a new issue with this error. See [`CONTRIBUTING.md`](https://github.com/AAROC/DevOps/blob/master/CONTRIBUTING.md#reporting-issues) for more info :smiley:
